apiVersion: v1
kind: Service
metadata:
  name: storage-service-loadbalancer
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: storage-service
  ports:
    - name: http
      port: 80 # Service Port
      targetPort: 3000 # Container Port
